FORMAT: 1A
HOST: https://push.notifica.re/

# Notificare SDK API
This is an official Notificare API that enables access to certain features of our platform specially designed to be used in native mobile SDKs. Its sole purpose is to provide access to strategic endpoints via a mobile app.
The API endpoints below are all authenticated with `applicationKey` and `applicationSecret`, if you do not have these yet, you should grab them from your app in Notificare Dashboard under the section Settings > App Keys.
Use Basic HTTP Authentication where `applicationKey` should be your username and `applicationSecret` your password.

For technical support please [contact us](http://notifica.re/contact).

## Docs have moved!

REST API documentation has moved to a [new location](https://api-docs.notifica.re/sdk/), please update your bookmarks.
